title: Frostomatic
email: sirtimf@outlook.com
description: >-
  I am Tim Frost and this is my BEE to the EL to the OH to the GEE.
baseurl: ""
url: "https://frostomatic.github.io"

twitter_username: sirtimf
github_username: frostomatic

# theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
#  - jekyll-feed
