title: Frostomatic
email: sirtimf@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  I am Tim Frost and this is my BEE to the EL to the OH to the GEE.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://frostomatic.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sirtimf
github_username:  frostomatic

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
