title: Frostomatic
email: sirtimf@outlook.com
description: >-
  I am Tim Frost and this is my BEE to the EL to the OH to the GEE.
baseurl: ""
url: "https://frostomatic.github.io"

twitter_username: sirtimf
github_username: frostomatic

# theme: jekyll-theme-cayman
theme: cayman

plugins:
- jekyll-feed
